:PROPERTIES:
:ID:       fe56aec7-253f-47d9-8d88-6b80106f61b8
:END:
#+title: A history of My Relationship with Meditation and Mindfulness

I have had an on-and-off relationship with mindfulness most of my life. The first time I tried meditating was during my early teens. I was fascinated by the idea of getting a better grasp of my inner world. I was unable to establish a habit but I think the reason I stopped trying to maintain this practice also came about as a result of my budding critical-thinking skills and understanding of of science. In my attempt to remove all the pseudoscience from my life I erroneously classified all meditation practices as unscientific. Later towards the end of my teens I realized that this was a mistake and discovered a whole world of benefits that I had deprived myself of--I learned about mindfulness and I began to understand that it truly is scientific. I was mainly driven by my desire to improve myself and I realized that improving my mental habits is perhaps the best gift I can give my future self and maybe even my current self. More than just that, I want to uncover the true nature of reality and overcome the illusions that the human experience imposes but I also want to learn how to enjoy these illusions so that I can make the most of a life lived. I did maintain mindfulness practices and stopped multiple times but now I am determined to make it something that stays with me. I am taking this course just to give myself another reason to keep thinking about mindfulness and it does seem like a good course so I guess I might even learn something.