:PROPERTIES:
:ID:       133a3655-e6f6-4492-87d5-ae90fdd257b3
:END:
#+title: Day Architecture

> How we spend our days, is of course, how we spend our lives.
\- Annie Dillard.

How we end up structuring our days is how we structure our lives. The kind of days we allow ourselves to have. We can have a principles that our consistent on all days, we can have some exceptions for these principles on certain days. It all depends on how one wants to spend their life.

I want to live a life dedicated to full self-expression, play, learning, love and exploration. So in order to achieve something of this sort,I should think of certain key elements that allow me into flow into activities without any friction. 

- Start the morning with a run. This will get your brain's engines moving and fire your energy hopefully;
- Then come back and rest and then meditate;
- Brainstorm on the MIQ you gave yourself last night if there was any;
- Have breakfast;
- Do the thing that you find the most difficulty in doing at this point in your life;
- Then choose whatever activity from your kanban to-do board that interests you since following a schedule is [[114205032021|no good]].
- Stay away from screens at least 30 minutes before you sleep time.
- Go to bed on time.

There are certain things that need to be done before others so there also comes the task of prioritization and that needs to be integrated on to your kanban board to-do board.

It is also important to not feel bad about not being busy. That is how you live 





