:PROPERTIES:
:ID:       b358f5b3-5ac4-4b51-a984-2c20c307be59
:END:
#+title: The Storming of the US Capitol -January 6th 2021

The event marked the crescendo of the "Save America Rally"--the response from MAGA types to Congress' certification of Biden's electoral votes--in which Trump [incited](https://www.palmbeachpost.com/story/news/politics/2021/01/06/what-trump-said-rally-speech-spark-u-s-capitol-storming/6568337002/) his supporters to storm the Capitol. This led to a subsequent clash between protesters and Washington D.C policemen who were overwhelmed by them as they broke through their barricades in a frenzy. Protesters were then able to push through and break into the Capitol. An immediate evacuation of Congress--who were in the middle of a debate regarding the electoral votes--followed. This reminded me of that scene from The Boys Season 2 where the heads exploded in Congress. Authorities clashed with the protesters inside the Capitol which resulted in the death of one of the protesters before they were able to handle the situation.